import http from 'node:http';
import {createReadStream,existsSync,statSync,readFileSync,realpathSync} from 'node:fs';
import {extname,join,normalize,resolve,relative,isAbsolute} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
import {
  runtime,isConfigured,requestId,authenticate,requirePermission,loadAuthoritativeDb,rpc,
  logSecurityEvent,enforceRateLimit,corsHeaders,baseSecurityHeaders,serviceRpc,verifyValidationEvidenceRequest
} from './security.mjs';

const require=createRequire(import.meta.url);
const Calc=require('../calculation-core.js');
const root=resolve(fileURLToPath(new URL('..',import.meta.url)));
const publicRoot=resolve(join(root,'public'));
const VERSION=JSON.parse(readFileSync(join(root,'VERSION.json'),'utf8'));
const finiteNumber=(value,fallback,min,max)=>{const parsed=Number(value);return Number.isFinite(parsed)?Math.min(max,Math.max(min,parsed)):fallback;};
const port=Math.trunc(finiteNumber(process.env.PORT,8787,1,65535));
const host=process.env.HOST||'127.0.0.1';
const maxBodyBytes=finiteNumber(process.env.MAX_BODY_BYTES,2*1024*1024,64*1024,50*1024*1024);
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.svg':'image/svg+xml','.webmanifest':'application/manifest+json; charset=utf-8'};

function browserRuntimeConfig(){
  const environment=runtime.environment==='production'?'production':runtime.authoritative?'staging':'demo';
  return {
    releaseVersion:VERSION.version,
    environment,
    dataMode:runtime.authoritative?'server-authoritative':'demo-compatible',
    apiBaseUrl:'',
    requireServerForProduction:true,
    apiAuthRequired:runtime.authoritative,
    allowDemoLogin:!runtime.authoritative,
    allowLocalBusinessData:!runtime.authoritative,
    allowOfflineWritesInProduction:false,
    sessionPersistence:'session',
    sessionIdleTimeoutMs:runtime.sessionIdleTimeoutMs,
    sessionAbsoluteTimeoutMs:runtime.sessionAbsoluteTimeoutMs,
    requireMfaForPrivilegedRoles:true,
    supabaseUrl:runtime.authoritative?runtime.supabaseUrl:'',
    supabaseAnonKey:runtime.authoritative?runtime.supabaseAnonKey:'',
    companyCode:String(process.env.ALPHA_COMPANY_CODE||'ALPHA'),
    companyName:String(process.env.ALPHA_COMPANY_NAME||'ALPHA DESIGN'),
    ownerFullName:String(process.env.ALPHA_OWNER_NAME||'Giám đốc ALPHA DESIGN'),
    autoProvisionFirstUser:false,
    enableRealtime:runtime.authoritative,
    syncIntervalMs:finiteNumber(process.env.SYNC_INTERVAL_MS,10000,5000,3600000),
    bootstrapDemoData:!runtime.authoritative
  };
}
function runtimeConfigScript(){
  return `// Generated by ALPHA DESIGN ERP backend ${VERSION.version}. No service-role secret is exposed.\nwindow.ALPHA_RUNTIME_CONFIG = ${JSON.stringify(browserRuntimeConfig(),null,2)};\n`;
}

function send(res,status,payload,headers={}){
  const body=status===204?'':typeof payload==='string'?payload:JSON.stringify(payload);
  res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers});
  res.end(body);
}
function readJson(req){
  return new Promise((resolveBody,reject)=>{
    let size=0,raw='',settled=false,tooLarge=false;
    const declared=Number(req.headers['content-length']||0);
    if(Number.isFinite(declared)&&declared>maxBodyBytes){req.resume();reject(Object.assign(new Error('Payload quá lớn.'),{status:413,code:'PAYLOAD_TOO_LARGE'}));return;}
    req.setEncoding('utf8');
    req.on('data',chunk=>{
      if(tooLarge)return;
      size+=Buffer.byteLength(chunk);
      if(size>maxBodyBytes){
        tooLarge=true;raw='';
        if(!settled){settled=true;reject(Object.assign(new Error('Payload quá lớn.'),{status:413,code:'PAYLOAD_TOO_LARGE'}));}
        return;
      }
      raw+=chunk;
    });
    req.on('end',()=>{
      if(tooLarge||settled)return;
      try{settled=true;resolveBody(raw?JSON.parse(raw):{});}
      catch{settled=true;reject(Object.assign(new Error('JSON không hợp lệ.'),{status:400,code:'INVALID_JSON'}));}
    });
    req.on('aborted',()=>{if(!settled){settled=true;reject(Object.assign(new Error('Yêu cầu đã bị ngắt.'),{status:400,code:'REQUEST_ABORTED'}));}});
    req.on('error',error=>{if(!settled){settled=true;reject(error);}});
  });
}
function cleanRange(input={}){
  const iso=value=>{
    const text=String(value||'');if(!text)return '';
    if(!Calc.isISODate(text))throw Object.assign(new Error('Ngày không hợp lệ.'),{status:422,code:'INVALID_DATE'});
    return text;
  };
  const range={from:iso(input.from),to:iso(input.to)};
  if(range.from&&range.to&&range.from>range.to)throw Object.assign(new Error('Khoảng ngày không hợp lệ.'),{status:422,code:'INVALID_DATE_RANGE'});
  return range;
}
function databaseSummary(db={}){
  const range=cleanRange(db?.meta?.range||{});
  const integrity=Calc.integrityChecks(db,range);
  const portfolio=Calc.portfolioHealth(db,range);
  return {integrity,portfolio:{...portfolio,rows:portfolio.rows.map(({project,...row})=>({project:{id:project.id,code:project.code,name:project.name},...row}))}};
}
async function resolveDb(req,body,permissions){
  if(runtime.authoritative){
    const auth=await authenticate(req);requirePermission(auth,permissions);
    const db=await loadAuthoritativeDb(auth);return {db,auth,source:'postgresql'};
  }
  if(isConfigured()&&String(process.env.REQUIRE_AUTH_IN_STAGING||'false').toLowerCase()==='true'){
    const auth=await authenticate(req);requirePermission(auth,permissions);
    const db=await loadAuthoritativeDb(auth);return {db,auth,source:'postgresql'};
  }
  if(String(process.env.ALLOW_CLIENT_DB||'true').toLowerCase()!=='true')throw Object.assign(new Error('Client-supplied database is disabled.'),{status:403});
  return {db:body.db||{},auth:null,source:'client-demo'};
}
async function handleApi(req,res,url,requestIdValue,baseHeaders){
  const cors=corsHeaders(req);const headers={...baseHeaders,...cors};
  if(req.method==='OPTIONS')return send(res,204,'',{'access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'authorization,content-type,x-request-id','access-control-max-age':'600',...headers});
  enforceRateLimit(req,url.pathname);
  if(req.method==='GET'&&url.pathname==='/api/health')return send(res,200,{ok:true,service:'alpha-erp-api',version:VERSION.version,formulaVersion:VERSION.formulaVersion,environment:runtime.environment,dataMode:runtime.authoritative?'server-authoritative':'demo-compatible',supabaseConfigured:isConfigured(),time:new Date().toISOString()},headers);
  if(req.method==='GET'&&url.pathname==='/api/session'){
    const auth=await authenticate(req);await logSecurityEvent(auth,'api.session',true,'info',{request_id:requestIdValue});
    return send(res,200,{ok:true,context:auth.context,user:{id:auth.user.id,email:auth.user.email}},headers);
  }
  if(req.method==='GET'&&url.pathname==='/api/production-readiness'){
    const auth=await authenticate(req);requirePermission(auth,['admin','dashboard.read']);
    const result=await rpc(auth,'production_readiness',{});return send(res,200,{ok:true,result:Array.isArray(result)?result[0]:result},headers);
  }
  if(req.method==='POST'&&url.pathname==='/api/release-gate'){
    const body=await readJson(req);verifyValidationEvidenceRequest(req,body);
    const companyId=String(body.companyId||'');if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(companyId))return send(res,400,{ok:false,error:'companyId không hợp lệ.'},headers);
    const release=String(body.release||VERSION.version),gateCode=String(body.gateCode||''),status=String(body.status||''),evidenceUri=body.evidenceUri==null?null:String(body.evidenceUri),checksum=body.checksumSha256==null?null:String(body.checksumSha256);
    if(!release||release.length>80||!/^[-._a-z0-9]+$/i.test(release))return send(res,400,{ok:false,error:'release không hợp lệ.'},headers);
    if(!/^[a-z][a-z0-9_]{1,63}$/.test(gateCode))return send(res,400,{ok:false,error:'gateCode không hợp lệ.'},headers);
    if(!['passed','failed','warning','running','blocked'].includes(status))return send(res,400,{ok:false,error:'status không hợp lệ.'},headers);
    if(evidenceUri&&evidenceUri.length>2048)return send(res,400,{ok:false,error:'evidenceUri quá dài.'},headers);
    if(checksum&&!/^[0-9a-f]{64}$/i.test(checksum))return send(res,400,{ok:false,error:'checksumSha256 không hợp lệ.'},headers);
    const result=await serviceRpc('record_release_gate_pipeline',{p_company:companyId,p_release:release,p_gate_code:gateCode,p_status:status,p_summary:body.summary||{},p_evidence_uri:evidenceUri,p_checksum_sha256:checksum,p_expires_at:body.expiresAt||null});
    return send(res,200,{ok:true,result:Array.isArray(result)?result[0]:result},headers);
  }
  if(req.method==='POST'&&url.pathname==='/api/release-approval'){
    const body=await readJson(req);const auth=await authenticate(req);const approvalType=String(body.approvalType||'').toLowerCase();
    if(!['accounting','director'].includes(approvalType))return send(res,400,{ok:false,error:'approvalType không hợp lệ.'},headers);
    requirePermission(auth,approvalType==='accounting'?['accounting.close']:['release.approve']);
    const result=await rpc(auth,'approve_release',{p_release:String(body.release||VERSION.version),p_approval_type:approvalType,p_note:body.note||null});
    return send(res,200,{ok:true,result:Array.isArray(result)?result[0]:result},headers);
  }
  if(req.method==='POST'&&url.pathname==='/api/operational-mode'){
    const body=await readJson(req);const auth=await authenticate(req);requirePermission(auth,['release.approve','security.manage','admin']);
    const result=await rpc(auth,'set_operational_mode',{p_mode:String(body.mode||''),p_release:String(body.release||VERSION.version)});
    return send(res,200,{ok:true,result:Array.isArray(result)?result[0]:result},headers);
  }
  if(req.method==='POST'&&url.pathname==='/api/validate-database'){
    const body=await readJson(req);const resolved=await resolveDb(req,body,['accounting.read','dashboard.read']);
    const summary=databaseSummary(resolved.db);await logSecurityEvent(resolved.auth,'api.validate_database',summary.integrity.passCritical,summary.integrity.passCritical?'info':'warning',{source:resolved.source,request_id:requestIdValue});
    return send(res,summary.integrity.passCritical?200:422,{ok:summary.integrity.passCritical,source:resolved.source,...summary},headers);
  }
  if(req.method==='POST'&&url.pathname==='/api/project-financials'){
    const body=await readJson(req);const projectId=String(body.projectId||'').trim();if(!projectId||projectId.length>180)return send(res,400,{ok:false,error:'projectId không hợp lệ.'},headers);
    const resolved=await resolveDb(req,body,['projects.read','dashboard.read']);const result=Calc.projectFinancials(resolved.db,projectId,cleanRange(body.range||{}));
    return send(res,result.valid?200:422,{ok:result.valid,source:resolved.source,result},headers);
  }
  if(req.method==='POST'&&url.pathname==='/api/portfolio-control'){
    const body=await readJson(req);const resolved=await resolveDb(req,body,['projects.read','dashboard.read']);const result=Calc.portfolioHealth(resolved.db,cleanRange(body.range||{}));
    return send(res,200,{ok:true,source:resolved.source,result:{...result,rows:result.rows.map(({project,...row})=>({project:{id:project.id,code:project.code,name:project.name},...row}))}},headers);
  }
  if(req.method==='POST'&&url.pathname==='/api/invoice-aging'){
    const body=await readJson(req);const resolved=await resolveDb(req,body,['accounting.read','crm.read']);const options={...(body.options||body.range||{}),...cleanRange(body.options||body.range||{})};
    const result=Calc.invoiceAging(resolved.db,options);return send(res,200,{ok:true,source:resolved.source,result},headers);
  }
  return false;
}
function safeFile(pathname){
  let decoded='';
  try{decoded=decodeURIComponent(pathname);}catch{return null;}
  let clean=normalize(decoded);
  while(clean.startsWith('/')||clean.startsWith('\\'))clean=clean.slice(1);
  const candidate=resolve(join(publicRoot,clean||'index.html'));
  const candidateRelative=relative(publicRoot,candidate);
  if(candidateRelative.startsWith('..')||isAbsolute(candidateRelative))return null;
  let file=candidate;
  if(existsSync(file)&&statSync(file).isDirectory())file=join(file,'index.html');
  if(!existsSync(file)||!statSync(file).isFile())return file;
  const real=realpathSync(file),realRelative=relative(publicRoot,real);
  return realRelative.startsWith('..')||isAbsolute(realRelative)?null:real;
}
if(!existsSync(publicRoot)||!statSync(publicRoot).isDirectory())throw new Error('Thiếu thư mục public. Chạy: node scripts/build-public.mjs');

const server=http.createServer(async(req,res)=>{
  const requestIdValue=requestId(req);const baseHeaders=baseSecurityHeaders({requestIdValue});
  try{
    const url=new URL(req.url||'/','http://localhost');
    if(url.pathname.startsWith('/api/')){const handled=await handleApi(req,res,url,requestIdValue,baseHeaders);if(handled!==false)return;return send(res,404,{ok:false,error:'API không tồn tại.',requestId:requestIdValue},baseHeaders);}
    if(req.method==='GET'&&url.pathname==='/runtime-config.js'){res.writeHead(200,{...baseSecurityHeaders({requestIdValue}),'content-type':'text/javascript; charset=utf-8','cache-control':'no-store'});return res.end(runtimeConfigScript());}
    if(req.method!=='GET'&&req.method!=='HEAD')return send(res,405,{ok:false,error:'Phương thức không được hỗ trợ.',requestId:requestIdValue},baseHeaders);
    const file=safeFile(url.pathname==='/'?'/index.html':url.pathname);
    if(!file||!existsSync(file)||!statSync(file).isFile())return send(res,404,{ok:false,error:'Không tìm thấy tài nguyên.',requestId:requestIdValue},baseHeaders);
    const extension=extname(file).toLowerCase();const headers={...baseSecurityHeaders({requestIdValue,html:extension==='.html'}),'content-type':mime[extension]||'application/octet-stream','cache-control':extension==='.html'||extension==='.js'?'no-cache':'public, max-age=300'};
    res.writeHead(200,headers);if(req.method==='HEAD')return res.end();createReadStream(file).pipe(res);
  }catch(error){
    const status=Number(error.status)||500;
    const production=runtime.environment==='production';
    const publicMessage=production&&status>=500?(status===504?'Dịch vụ dữ liệu phản hồi quá thời gian.':'Dịch vụ tạm thời không khả dụng.'):error.message||'Lỗi máy chủ.';
    if(status>=500)console.error(`[${requestIdValue}]`,error);
    if(!res.headersSent)send(res,status,{ok:false,error:publicMessage,code:error.code||'SERVER_ERROR',requestId:requestIdValue},baseHeaders);else res.end();
  }
});
server.requestTimeout=Math.trunc(finiteNumber(process.env.REQUEST_TIMEOUT_MS,30000,5000,120000));
server.headersTimeout=Math.min(server.requestTimeout,Math.trunc(finiteNumber(process.env.HEADERS_TIMEOUT_MS,15000,5000,60000)));
server.keepAliveTimeout=Math.trunc(finiteNumber(process.env.KEEP_ALIVE_TIMEOUT_MS,5000,1000,30000));
server.maxHeadersCount=100;
server.listen(port,host,()=>console.log(`ALPHA DESIGN ERP v${VERSION.version}: http://${host}:${port} (${runtime.authoritative?'server-authoritative':'demo-compatible'})`));
