import assert from 'node:assert/strict';
import fs from 'node:fs';
const html=fs.readFileSync('index.html','utf8');
const app=fs.readFileSync('app.js','utf8');
const css=fs.readFileSync('alpha-design-system.css','utf8');
const cloud=fs.readFileSync('cloud-v2.js','utf8');
const version=JSON.parse(fs.readFileSync('VERSION.json','utf8'));
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
assert.match(version.version,/^\d+\.\d+\.\d+$/);
assert.equal(version.databaseMigration,75);
assert.equal(pkg.version,version.version);
for(const id of ['i-edit','i-trash','i-readiness','i-access','i-eye']) assert.ok(html.includes(`id="${id}"`),id);
assert.ok(html.includes('id="markAllNotificationsRead"'));
for(const marker of ['notificationItems()','markNotificationRead','data-notification-view','data-notification-record','notificationReads','navigate(item.dataset.notificationView,item.dataset.notificationRecord)']) assert.ok(app.includes(marker),marker);
for(const marker of ['data-record-id="${esc(t.id)}"','data-record-id="${esc(x.id)}"','record-focus']) assert.ok(app.includes(marker)||css.includes(marker),marker);
assert.ok(app.includes("kpi('Hợp đồng đã ký'"));
assert.ok(!app.includes("kpi('Hợp đồng cam kết'"));
for(const marker of ['COMMERCIAL CONTROL • v','PLANNING & COST CONTROL • v','PROCUREMENT & ASSET CONTROL • v','SMART CONTROL ENGINE • v','FINANCIAL INTELLIGENCE ENGINE • v']) assert.ok(!app.includes(marker),marker);
assert.ok(!app.includes('Thuật toán v3.9.2'));
assert.ok(!cloud.includes('GOVERNANCE & LINKAGE ENGINE'));
assert.ok(!cloud.includes('<span class="eyebrow">RELEASE'));
assert.ok(app.includes('staff-cost-table'));
assert.ok(css.includes('.staff-cost-table table{min-width:0!important;width:100%;table-layout:fixed}'));
assert.ok(app.includes('balance-summary'));
assert.ok(css.includes('.balance-summary'));
assert.ok(html.includes('data-view="readiness" data-permission="dashboard"><svg class="nav-svg"><use href="#i-readiness"'));
assert.ok(html.includes('data-view="users" data-permission="admin"><svg class="nav-svg"><use href="#i-access"'));
assert.ok(!app.includes('Bản v4.3.0 bổ sung Financial Analytics'));
assert.ok(app.includes("kpi('Ngân sách dự kiến'"));
assert.ok(app.includes('Chi phí ước tính khi hoàn thành của dự án đã ký'));
assert.ok(fs.existsSync('package-lock.json'));
assert.ok(fs.existsSync('LIBRARIES_VI.md'));

assert.ok(app.includes('class="icon-btn contract-action edit-row" data-write-action'));
assert.ok(app.includes('class="icon-btn contract-action danger delete-row" data-write-action'));
assert.ok(!app.includes('Bản v4.2.0 bổ sung Financial Analytics'));
assert.ok(!app.includes('release-note-panel'));
assert.ok(fs.existsSync('libraries/runtime-libraries.json'));
assert.ok(fs.existsSync('libraries/check-libraries.mjs'));
console.log(`PASS v${version.version} notification navigation and UI cleanup static assertions`);
