import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=(p)=>fs.readFileSync(path.join(root,p),'utf8');
const json=(p)=>JSON.parse(read(p));
const meta=json('VERSION.json');
const version=meta.version;
const pkg=json('package.json'),lock=json('package-lock.json');
assert.equal(pkg.version,version);assert.equal(lock.version,version);assert.equal(lock.packages[''].version,version);assert.equal(meta.version,version);assert.equal(meta.release,version);
assert.equal(pkg.devDependencies,undefined,'Runtime package must not depend on registry-only developer tools');
assert.deepEqual(Object.keys(lock.packages),[''],'Runtime lockfile must be reproducible and dependency-free');
const index=read('index.html'),sw=read('sw.js'),manifest=json('manifest.webmanifest');
assert.ok(index.includes(`VERSION ${version}`));assert.ok(index.includes(`v${version}`));assert.ok(sw.includes(version));assert.ok(String(manifest.name||'').includes('ALPHA DESIGN ERP'));
const publicFiles=['index.html','app.js','calculation-core.js','reporting-period.js','statutory-template-manager.js','statutory-template-reference.js','tax-compliance-package-manager.js','tax-compliance-reference.js','tax-calendar.js','accounting-operations.js','payroll-detail.js','annual-benefits.js','recycle-bin.js','permission-map.js','production-guard.js','export-center.js','theme-manager.js','demo-enterprise-seed.js','cloud-adapter.js','alpha-sync.bundle.js','auth-security.js','cloud-v2.js','alpha-enterprise.js','alpha-design-system.css','runtime-config.js','sw.js','theme-bootstrap.js','manifest.webmanifest','logo-alpha-transparent.png','logo-alpha-on-dark.png','icon-192.png','icon-512.png','templates/statutory/TT133_2026_BASELINE_TEMPLATE.json','templates/tax/VN_TAX_2026_BASELINE_PACKAGE.json'];
for(const file of publicFiles){assert.ok(fs.existsSync(path.join(root,file)),`Missing source ${file}`);assert.ok(fs.existsSync(path.join(root,'public',file)),`Missing public ${file}`);assert.deepEqual(fs.readFileSync(path.join(root,file)),fs.readFileSync(path.join(root,'public',file)),`Public build differs: ${file}`);}
const htmlIds=[...index.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]);assert.equal(new Set(htmlIds).size,htmlIds.length,'Duplicate HTML IDs');
assert.equal(/<(script|link)[^>]+https?:\/\//i.test(index),false,'Runtime HTML must not load CDN assets');
assert.deepEqual(meta.responsiveBreakpoints,[360,390,430,768,820,1024],'Responsive breakpoint declaration is incomplete');
for(const removed of ['api','EVIDENCE','netlify.toml','vercel.json','START_DEMO_WINDOWS.bat','START_DEMO_MAC_LINUX.sh'])assert.equal(fs.existsSync(path.join(root,removed)),false,`Obsolete deployment or evidence artifact must be removed: ${removed}`);
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/033_entity_payload_integrity_v453.sql')),'Migration 033 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 033_entity_payload_integrity_v453.sql'),'Consolidated schema is missing migration 033');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/034_formula_linkage_web_security_v454.sql')),'Migration 034 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 034_formula_linkage_web_security_v454.sql'),'Consolidated schema is missing migration 034');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/035_ui_formula_deep_audit_v455.sql')),'Migration 035 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 035_ui_formula_deep_audit_v455.sql'),'Consolidated schema is missing migration 035');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/036_ui_balance_contrast_formula_simulation_v456.sql')),'Migration 036 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 036_ui_balance_contrast_formula_simulation_v456.sql'),'Consolidated schema is missing migration 036');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/037_ui_ux_workflow_formula_input_v457.sql')),'Migration 037 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 037_ui_ux_workflow_formula_input_v457.sql'),'Consolidated schema is missing migration 037');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/038_compact_kpi_runtime_hardening_v458.sql')),'Migration 038 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 038_compact_kpi_runtime_hardening_v458.sql'),'Consolidated schema is missing migration 038');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/039_full_table_layout_alignment_v459.sql')),'Migration 039 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 039_full_table_layout_alignment_v459.sql'),'Consolidated schema is missing migration 039');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/040_table_separation_action_usability_v4510.sql')),'Migration 040 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 040_table_separation_action_usability_v4510.sql'),'Consolidated schema is missing migration 040');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/041_action_edit_collision_fix_v4511.sql')),'Migration 041 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 041_action_edit_collision_fix_v4511.sql'),'Consolidated schema is missing migration 041');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/042_final_ui_formula_linkage_closure_v4512.sql')),'Migration 042 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 042_final_ui_formula_linkage_closure_v4512.sql'),'Consolidated schema is missing migration 042');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/043_modal_scroll_action_visibility_v4513.sql')),'Migration 043 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 043_modal_scroll_action_visibility_v4513.sql'),'Consolidated schema is missing migration 043');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/044_final_release_candidate_v4514.sql')),'Migration 044 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 044_final_release_candidate_v4514.sql'),'Consolidated schema is missing migration 044');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/045_account_protection_mfa_runtime_fix_v4515.sql')),'Migration 045 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 045_account_protection_mfa_runtime_fix_v4515.sql'),'Consolidated schema is missing migration 045');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/046_release_claim_ui_mobile_security_formula_sql_audit_v4516.sql')),'Migration 046 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 046_release_claim_ui_mobile_security_formula_sql_audit_v4516.sql'),'Consolidated schema is missing migration 047');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/047_accounting_report_table_fit_v4517.sql')),'Migration 047 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 047_accounting_report_table_fit_v4517.sql'),'Consolidated schema is missing migration 047');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/048_tax_integration_typography_formula_linkage_v4518.sql')),'Migration 048 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 048_tax_integration_typography_formula_linkage_v4518.sql'),'Consolidated schema is missing migration 049');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/049_accessibility_table_fit_truthful_integrations_v4519.sql')),'Migration 049 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 049_accessibility_table_fit_truthful_integrations_v4519.sql'),'Consolidated schema is missing migration 049');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/050_global_table_column_action_alignment_v4520.sql')),'Migration 050 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 050_global_table_column_action_alignment_v4520.sql'),'Consolidated schema is missing migration 050');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/051_deep_audit_transition_permissions_v4521.sql')),'Migration 051 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 051_deep_audit_transition_permissions_v4521.sql'),'Consolidated schema is missing migration 051');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/052_qa_closure_release_v4525.sql')),'Migration 052 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 052_qa_closure_release_v4525.sql'),'Consolidated schema is missing migration 052');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/053_effective_dated_tax_qa_portability_v4526.sql')),'Migration 053 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 053_effective_dated_tax_qa_portability_v4526.sql'),'Consolidated schema is missing migration 053');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/054_production_invariants_v4527.sql')),'Migration 054 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 054_production_invariants_v4527.sql'),'Consolidated schema is missing migration 054');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/055_financial_reporting_integrity_v4536.sql')),'Migration 055 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 055_financial_reporting_integrity_v4536.sql'),'Consolidated schema is missing migration 055');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/056_production_financial_certification_v4538.sql')),'Migration 056 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 056_production_financial_certification_v4538.sql'),'Consolidated schema is missing migration 056');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/057_company_profile_dynamic_reporting_period_v4539.sql')),'Migration 057 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 057_company_profile_dynamic_reporting_period_v4539.sql'),'Consolidated schema is missing migration 057');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/058_statutory_template_manager_filter_chart_tax_v4540.sql')),'Migration 058 is missing');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/059_stability_browser_qa_data_quality_v4541.sql')),'Migration 059 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 059_stability_browser_qa_data_quality_v4541.sql'),'Consolidated schema is missing migration 059');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/060_detailed_employee_payroll_v4542.sql')),'Migration 060 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 060_detailed_employee_payroll_v4542.sql'),'Consolidated schema is missing migration 060');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/061_payroll_header_layout_refinement_v4543.sql')),'Migration 061 is missing');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/062_global_table_grid_alignment_v4544.sql')),'Migration 062 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 061_payroll_header_layout_refinement_v4543.sql'),'Consolidated schema is missing migration 061');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 062_global_table_grid_alignment_v4544.sql'),'Consolidated schema is missing migration 062');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/063_annual_bonus_travel_fund_v4545.sql')),'Migration 063 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 063_annual_bonus_travel_fund_v4545.sql'),'Consolidated schema is missing migration 063');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/064_sticky_table_workflow_formula_hardened_v4546.sql')),'Migration 064 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 064_sticky_table_workflow_formula_hardened_v4546.sql'),'Consolidated schema is missing migration 064');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/065_accounting_operations_tax_package_update_v4547.sql')),'Migration 065 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 065_accounting_operations_tax_package_update_v4547.sql'),'Consolidated schema is missing migration 065');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/066_responsive_sidebar_table_centering_v4548.sql')),'Migration 066 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 066_responsive_sidebar_table_centering_v4548.sql'),'Consolidated schema is missing migration 066');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/067_table_viewport_formula_linkage_hardened_v4549.sql')),'Migration 067 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 067_table_viewport_formula_linkage_hardened_v4549.sql'),'Consolidated schema is missing migration 067');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/068_enterprise_data_alignment_operational_audit_v4550.sql')),'Migration 068 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 068_enterprise_data_alignment_operational_audit_v4550.sql'),'Consolidated schema is missing migration 068');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/069_accounting_tax_legal_hardening_v4561.sql')),'Migration 069 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 069_accounting_tax_legal_hardening_v4561.sql'),'Consolidated schema is missing migration 069');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/070_vat_payment_evidence_tk242_parity_v4562.sql')),'Migration 070 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 070_vat_payment_evidence_tk242_parity_v4562.sql'),'Consolidated schema is missing migration 070');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/071_table_scroll_continuity_release_v4563.sql')),'Migration 071 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 071_table_scroll_continuity_release_v4563.sql'),'Consolidated schema is missing migration 071');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/072_prepaint_table_viewport_release_v4564.sql')),'Migration 072 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 072_prepaint_table_viewport_release_v4564.sql'),'Consolidated schema is missing migration 072');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/073_full_control_terminology_release_v4565.sql')),'Migration 073 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 073_full_control_terminology_release_v4565.sql'),'Consolidated schema is missing migration 073');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/074_recycle_bin_restore_v4566.sql')),'Migration 074 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 074_recycle_bin_restore_v4566.sql'),'Consolidated schema is missing migration 074');
assert.ok(fs.existsSync(path.join(root,'supabase/migrations/075_deep_qa_autoheal_v4567.sql')),'Migration 075 is missing');
assert.ok(read('SUPABASE_PRODUCTION_SCHEMA.sql').includes('SOURCE: 075_deep_qa_autoheal_v4567.sql'),'Consolidated schema is missing migration 075');
assert.equal(meta.databaseMigration,75,'VERSION databaseMigration is stale');
assert.equal(meta.uiRuntimeAudit.states,7,'VERSION targeted UI audit count is stale');
assert.equal(meta.uiRuntimeAudit.accountingLayoutPassedStates,10,'VERSION accounting browser evidence is stale');
assert.equal(meta.uiRuntimeAudit.inputWorkflowPassedChecks,30,'VERSION input browser evidence is stale');
assert.equal(meta.uiRuntimeAudit.status,`passed_exact_v${version}_static_formula_backend_security_accounting_tax_regression_and_structural_browser`,'VERSION must record the exact verified regression scope');
assert.equal(meta.uiRuntimeAudit.globalColumnCenteringStates,meta.uiRuntimeAudit.globalColumnCenteringPassedStates,'Every global column centering browser state must pass');
assert.ok(meta.uiRuntimeAudit.globalColumnCenteringStates>0,'Global column centering browser audit evidence is missing');
assert.equal(meta.uiRuntimeAudit.targetedAccountingTaxPassedChecks,7,'VERSION targeted accounting/tax browser evidence is stale');
assert.equal(meta.uiRuntimeAudit.fullBrowserRunnerCompleted,false,'Package must not overstate the full extended browser runner');
assert.equal(meta.uiRuntimeAudit.structuralAuditCurrentReleaseCompleted,true,'Exact-package structural browser audit evidence is required');
assert.equal(meta.uiRuntimeAudit.structuralStates,378,'Structural browser state count is stale');
assert.equal(meta.uiRuntimeAudit.browserAuditPassedSteps,3,'Current release browser evidence must record the three completed browser gates');
assert.equal(meta.uiRuntimeAudit.targetedTT99BrowserPassedChecks,0,'TT99 export is intentionally blocked, so no successful TT99 publication run may be claimed');
assert.equal(meta.uiRuntimeAudit.exportCenterPassedChecks,meta.uiRuntimeAudit.exportCenterChecks,'Current package must record all export-center browser checks');
assert.equal(meta.uiRuntimeAudit.extendedBrowserPassedSteps,meta.uiRuntimeAudit.extendedBrowserSteps,'Current package must record all extended browser regression steps');
assert.equal(meta.productionApproval,false,'Package must not self-approve Production');
const schemaDigest=createHash('sha256').update(fs.readFileSync(path.join(root,'SUPABASE_PRODUCTION_SCHEMA.sql'))).digest('hex');
assert.equal(read('SUPABASE_PRODUCTION_SCHEMA.sql.sha256').trim(),`${schemaDigest}  SUPABASE_PRODUCTION_SCHEMA.sql`,'Consolidated schema checksum is stale');
const golden=json('quality/golden/project-control-golden-result.json');assert.equal(golden.releaseVersion,version);assert.equal('executedAt' in golden,false,'Golden evidence must be deterministic');assert.equal(golden.passed,true);
const junk=[];const secret=[];const runtimeOld=[];const walk=(dir)=>{for(const ent of fs.readdirSync(dir,{withFileTypes:true})){if(ent.name==='.git'||ent.name==='node_modules')continue;const full=path.join(dir,ent.name),rel=path.relative(root,full).replaceAll('\\','/');if(ent.isDirectory()){walk(full);continue;}if(/(?:\.bak|\.tmp|\.log|\.pyc|~)$|(?:^|\/)\.DS_Store$/i.test(rel))junk.push(rel);if(/\.(?:js|mjs|cjs|html|css|json|env|example)$/i.test(rel)){const data=fs.readFileSync(full,'utf8');if(!rel.startsWith('tests/')&&!rel.startsWith('scripts/')&&/(?:sk_live_|AIza[0-9A-Za-z_-]{20,}|-----BEGIN (?:RSA|OPENSSH|EC) PRIVATE KEY-----)/.test(data))secret.push(rel);if(!rel.startsWith('supabase/migrations/')&&!rel.endsWith('SUPABASE_PRODUCTION_SCHEMA.sql')&&!rel.startsWith('EVIDENCE/')&&!rel.startsWith('tests/')&&!rel.startsWith('scripts/')&&/v4\.[0-3]\.[0-9]/.test(data))runtimeOld.push(rel);}}};walk(root);
assert.deepEqual(junk,[],'Junk files in release');assert.deepEqual(secret,[],'Possible secret in release');assert.deepEqual([...new Set(runtimeOld)],[],'Old runtime version reference');
for(const file of ['app.js','calculation-core.js','reporting-period.js','statutory-template-manager.js','statutory-template-reference.js','tax-compliance-package-manager.js','tax-compliance-reference.js','tax-calendar.js','accounting-operations.js','payroll-detail.js','annual-benefits.js','recycle-bin.js','auth-security.js','cloud-v2.js','cloud-adapter.js','permission-map.js','production-guard.js','export-center.js','theme-manager.js','theme-bootstrap.js','demo-enterprise-seed.js','alpha-enterprise.js','backend/server.mjs','backend/security.mjs'])execFileSync(process.execPath,['--check',path.join(root,file)],{stdio:'pipe'});
console.log(`PASS v${version} package integrity, migrations 001-075, reproducible lockfile, source/public parity, version, secret and junk checks`);
