import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const migration=fs.readFileSync(path.join(root,'supabase/migrations/033_entity_payload_integrity_v453.sql'),'utf8');
const migration34=fs.readFileSync(path.join(root,'supabase/migrations/034_formula_linkage_web_security_v454.sql'),'utf8');
const migration35=fs.readFileSync(path.join(root,'supabase/migrations/035_ui_formula_deep_audit_v455.sql'),'utf8');
const migration36=fs.readFileSync(path.join(root,'supabase/migrations/036_ui_balance_contrast_formula_simulation_v456.sql'),'utf8');
const migration37=fs.readFileSync(path.join(root,'supabase/migrations/037_ui_ux_workflow_formula_input_v457.sql'),'utf8');
const migration38=fs.readFileSync(path.join(root,'supabase/migrations/038_compact_kpi_runtime_hardening_v458.sql'),'utf8');
const migration39=fs.readFileSync(path.join(root,'supabase/migrations/039_full_table_layout_alignment_v459.sql'),'utf8');
const migration40=fs.readFileSync(path.join(root,'supabase/migrations/040_table_separation_action_usability_v4510.sql'),'utf8');
const migration41=fs.readFileSync(path.join(root,'supabase/migrations/041_action_edit_collision_fix_v4511.sql'),'utf8');
const migration42=fs.readFileSync(path.join(root,'supabase/migrations/042_final_ui_formula_linkage_closure_v4512.sql'),'utf8');
const migration43=fs.readFileSync(path.join(root,'supabase/migrations/043_modal_scroll_action_visibility_v4513.sql'),'utf8');
const migration44=fs.readFileSync(path.join(root,'supabase/migrations/044_final_release_candidate_v4514.sql'),'utf8');
const migration45=fs.readFileSync(path.join(root,'supabase/migrations/045_account_protection_mfa_runtime_fix_v4515.sql'),'utf8');
const migration46=fs.readFileSync(path.join(root,'supabase/migrations/046_release_claim_ui_mobile_security_formula_sql_audit_v4516.sql'),'utf8');
const migration47=fs.readFileSync(path.join(root,'supabase/migrations/047_accounting_report_table_fit_v4517.sql'),'utf8');
const migration48=fs.readFileSync(path.join(root,'supabase/migrations/048_tax_integration_typography_formula_linkage_v4518.sql'),'utf8');
const migration49=fs.readFileSync(path.join(root,'supabase/migrations/049_accessibility_table_fit_truthful_integrations_v4519.sql'),'utf8');
const migration50=fs.readFileSync(path.join(root,'supabase/migrations/050_global_table_column_action_alignment_v4520.sql'),'utf8');
const migration51=fs.readFileSync(path.join(root,'supabase/migrations/051_deep_audit_transition_permissions_v4521.sql'),'utf8');
const migration52=fs.readFileSync(path.join(root,'supabase/migrations/052_qa_closure_release_v4525.sql'),'utf8');
const migration53=fs.readFileSync(path.join(root,'supabase/migrations/053_effective_dated_tax_qa_portability_v4526.sql'),'utf8');
const migration54=fs.readFileSync(path.join(root,'supabase/migrations/054_production_invariants_v4527.sql'),'utf8');
const migration55=fs.readFileSync(path.join(root,'supabase/migrations/055_financial_reporting_integrity_v4536.sql'),'utf8');
const migration56=fs.readFileSync(path.join(root,'supabase/migrations/056_production_financial_certification_v4538.sql'),'utf8');
const migration57=fs.readFileSync(path.join(root,'supabase/migrations/057_company_profile_dynamic_reporting_period_v4539.sql'),'utf8');
const migration58=fs.readFileSync(path.join(root,'supabase/migrations/058_statutory_template_manager_filter_chart_tax_v4540.sql'),'utf8');
const migration59=fs.readFileSync(path.join(root,'supabase/migrations/059_stability_browser_qa_data_quality_v4541.sql'),'utf8');
const migration60=fs.readFileSync(path.join(root,'supabase/migrations/060_detailed_employee_payroll_v4542.sql'),'utf8');
const migration61=fs.readFileSync(path.join(root,'supabase/migrations/061_payroll_header_layout_refinement_v4543.sql'),'utf8');
const migration62=fs.readFileSync(path.join(root,'supabase/migrations/062_global_table_grid_alignment_v4544.sql'),'utf8');
const migration63=fs.readFileSync(path.join(root,'supabase/migrations/063_annual_bonus_travel_fund_v4545.sql'),'utf8');
const migration64=fs.readFileSync(path.join(root,'supabase/migrations/064_sticky_table_workflow_formula_hardened_v4546.sql'),'utf8');
const migration65=fs.readFileSync(path.join(root,'supabase/migrations/065_accounting_operations_tax_package_update_v4547.sql'),'utf8');
const migration66=fs.readFileSync(path.join(root,'supabase/migrations/066_responsive_sidebar_table_centering_v4548.sql'),'utf8');
const migration67=fs.readFileSync(path.join(root,'supabase/migrations/067_table_viewport_formula_linkage_hardened_v4549.sql'),'utf8');
const migration68=fs.readFileSync(path.join(root,'supabase/migrations/068_enterprise_data_alignment_operational_audit_v4550.sql'),'utf8');
const migration69=fs.readFileSync(path.join(root,'supabase/migrations/069_accounting_tax_legal_hardening_v4561.sql'),'utf8');
const migration70=fs.readFileSync(path.join(root,'supabase/migrations/070_vat_payment_evidence_tk242_parity_v4562.sql'),'utf8');
const migration71=fs.readFileSync(path.join(root,'supabase/migrations/071_table_scroll_continuity_release_v4563.sql'),'utf8');
const migration72=fs.readFileSync(path.join(root,'supabase/migrations/072_prepaint_table_viewport_release_v4564.sql'),'utf8');
const migration73=fs.readFileSync(path.join(root,'supabase/migrations/073_full_control_terminology_release_v4565.sql'),'utf8');
const migration74=fs.readFileSync(path.join(root,'supabase/migrations/074_recycle_bin_restore_v4566.sql'),'utf8');
const schema=fs.readFileSync(path.join(root,'SUPABASE_PRODUCTION_SCHEMA.sql'),'utf8');
const expectedCollections=["system", "settings", "notificationReads", "people", "clients", "vendors", "accounts", "projects", "tasks", "timesheets", "contracts", "journalEntries", "finance", "quotes", "approvals", "documents", "taxInvoices", "pitWithholdings", "citAdjustments", "taxFilings", "billingMilestones", "paymentAllocations", "openingBalances", "accountingPeriods", "projectBudgetVersions", "projectBudgetLines", "resourcePlans", "commitments", "projectStages", "purchaseRequests", "purchaseOrders", "tools", "fixedAssets", "toolAllocationSchedules", "depreciationSchedules", "financialForecastScenarios", "financialAnalysisSnapshots", "financialLinkAuditRuns", "trashEntries", "exportLogs", "importLogs"];

assert.ok(migration.includes('perform app.assert_operational_write_allowed(new.company_id)'), 'Entity trigger must retain the operational write kill-switch');
assert.equal(/grant\s+execute[^;]+entity_ref_exists[^;]+authenticated/is.test(migration),false,'Reference existence helpers must not be executable by authenticated users');
assert.equal(/grant\s+execute[^;]+entity_account_code_exists[^;]+authenticated/is.test(migration),false,'Account existence helper must not be executable by authenticated users');
for(const fn of ['entity_ref_exists','entity_account_code_exists','validate_entity_payload','entity_record_guard']){
  assert.ok(migration.includes(`revoke all on function app.${fn}(`),`Missing private-helper revoke for ${fn}`);
}
assert.ok(migration.includes("jsonb_typeof(p_payload)<>'array'")&&migration.includes('notificationReads must be an array'),'notificationReads singleton must accept only an array payload');
assert.ok(migration.includes("collection='notificationReads' and jsonb_typeof(data)='array'")&&migration.includes("collection<>'notificationReads' and jsonb_typeof(data)='object'"),'Table constraint must allow notificationReads arrays while keeping all other records as objects');
assert.ok(migration.includes('notificationReads payload must be a JSON array')&&migration.includes('perform app.validate_entity_payload(p_company,p_collection,p_record_id,p_payload)'),'The version-aware RPC must accept and validate notificationReads arrays');
assert.ok(migration.includes('revoke insert,update,delete on public.entity_records from authenticated'),'Authenticated clients must not bypass optimistic concurrency with direct table writes');
assert.ok(migration.includes('revoke all on function app.apply_entity_change')&&migration.includes('grant execute on function public.apply_entity_change'),'Only the protected public write RPC may be called by authenticated clients');
assert.ok(migration.includes('IMMUTABLE_ENTITY_IDENTITY'),'Entity company, collection and record identity must be immutable on update');
for(const name of expectedCollections) assert.ok(migration.includes(`p_collection='${name}'`)||migration.includes(`p_collection in ('${name}'`)||migration.includes(`p_collection=any(array['${name}'`)||migration.includes(`'${name}'`)||migration74.includes(`'${name}'`),`Server validation does not mention ${name}`);
for(const marker of ['INVALID_REFERENCE','DUPLICATE_KEY','FORMULA_MISMATCH','UNBALANCED_JOURNAL','DEPENDENCY_EXISTS','CROSS_PROJECT_REFERENCE','INVALID_DATE','INVALID_NUMBER']) assert.ok(migration.includes(marker),`Missing server integrity marker ${marker}`);
assert.ok(migration.includes("elsif tg_op='INSERT' then")&&migration.includes("elsif old.deleted_at is null then"),'Delete validation must not dereference OLD in the INSERT branch');
assert.ok(migration.includes("case when jsonb_typeof(r.data->'lines')='array'"),'Dependency scan must tolerate malformed historical journal-line payloads');
assert.ok(migration.includes("revoke all on function app.validate_entity_payload")&&migration.includes('from public,anon,authenticated'),'Payload validator must remain trigger-internal');
assert.ok(migration.includes("active_release_version='4.5.3'")&&migration.includes("('4.5.3','Integrity and security hardening"),'Migration must set the v4.5.3 release marker');
assert.ok(migration.includes("in ('4.5.0','4.5.1','4.5.2')"),'Migration must upgrade every prior 4.5.x release marker to 4.5.3');
assert.ok(schema.includes(migration.trim()),'Consolidated production schema must contain the exact migration 033 source');
for(const marker of ['validate_entity_payload_v453','json_has_unsafe_key','pg_advisory_xact_lock','OVER_ALLOCATION','INVALID_LINK_STATUS']){
  assert.ok(migration34.includes(marker),`Migration 034 is missing ${marker}`);
}
assert.ok(migration34.includes("active_release_version='4.5.4'")&&migration34.includes("('4.5.4','Formula and linkage security hardening"),'Migration 034 must set the v4.5.4 release marker');
assert.ok(migration34.includes("in ('4.5.0','4.5.1','4.5.2','4.5.3')"),'Migration 034 must upgrade every prior 4.5.x release marker');
for(const marker of ['validate_entity_payload_v454','recognized PIT requires Posted journal entry','recognized allocation requires Paid Income finance','DATE_ORDER']){
  assert.ok(migration35.includes(marker),`Migration 035 is missing ${marker}`);
}
assert.ok(migration35.includes("active_release_version='4.5.5'")&&migration35.includes("('4.5.5','Unified UI rhythm"),'Migration 035 must set the v4.5.5 release marker');
assert.ok(schema.includes(migration35.trim()),'Consolidated production schema must contain the exact migration 035 source');
assert.ok(migration36.includes("active_release_version='4.5.6'")&&migration36.includes("('4.5.6','Balanced tables"),'Migration 036 must set the v4.5.6 release marker');
assert.ok(migration36.includes("in ('4.5.0','4.5.1','4.5.2','4.5.3','4.5.4','4.5.5')"),'Migration 036 must upgrade every prior 4.5.x release marker');
assert.ok(schema.includes(migration36.trim()),'Consolidated production schema must contain the exact migration 036 source');
assert.ok(migration37.includes("active_release_version='4.5.7'")&&migration37.includes("('4.5.7','Workflow-centered data entry"),'Migration 037 must set the v4.5.7 release marker');
assert.ok(migration37.includes("in ('4.5.0','4.5.1','4.5.2','4.5.3','4.5.4','4.5.5','4.5.6')"),'Migration 037 must upgrade every prior 4.5.x release marker');
assert.ok(migration38.includes("active_release_version='4.5.8'")&&migration38.includes("('4.5.8','Compact KPI dashboard"),'Migration 038 must set the v4.5.8 release marker');
assert.ok(migration39.includes("active_release_version='4.5.9'")&&migration39.includes("('4.5.9','Full-width business tables"),'Migration 039 must set the v4.5.9 release marker');
assert.ok(schema.includes('SOURCE: 039_full_table_layout_alignment_v459.sql'),'Consolidated schema must include migration 039');
assert.ok(migration40.includes("active_release_version='4.5.10'")&&migration40.includes("('4.5.10','Named full-width people directory"),'Migration 040 must set the v4.5.10 release marker');
assert.ok(schema.includes('SOURCE: 040_table_separation_action_usability_v4510.sql'),'Consolidated schema must include migration 040');
assert.ok(migration41.includes("active_release_version='4.5.11'")&&migration41.includes("('4.5.11','Safe posted-journal adjustment"),'Migration 041 must set the v4.5.11 release marker');
assert.ok(schema.includes('SOURCE: 041_action_edit_collision_fix_v4511.sql'),'Consolidated schema must include migration 041');
assert.ok(migration42.includes("active_release_version='4.5.12'")&&migration42.includes("('4.5.12','Final journal-entry UI clarity"),'Migration 042 must set the v4.5.12 release marker');
assert.ok(schema.includes('SOURCE: 042_final_ui_formula_linkage_closure_v4512.sql'),'Consolidated schema must include migration 042');
assert.ok(migration43.includes("active_release_version='4.5.13'")&&migration43.includes("('4.5.13','Independent journal-modal scrolling"),'Migration 043 must set the v4.5.13 release marker');
assert.ok(schema.includes('SOURCE: 043_modal_scroll_action_visibility_v4513.sql'),'Consolidated schema must include migration 043');
assert.ok(schema.includes(migration37.trim())&&schema.includes(migration38.trim())&&schema.includes(migration39.trim())&&schema.includes(migration40.trim())&&schema.includes(migration41.trim())&&schema.includes(migration42.trim())&&schema.includes(migration43.trim())&&schema.includes(migration44.trim())&&schema.includes(migration45.trim())&&schema.includes(migration46.trim())&&schema.includes(migration47.trim())&&schema.includes(migration48.trim())&&schema.includes(migration49.trim())&&schema.includes(migration50.trim())&&schema.includes(migration51.trim())&&schema.includes(migration52.trim())&&schema.includes(migration53.trim())&&schema.includes(migration54.trim())&&schema.includes(migration55.trim())&&schema.includes(migration56.trim())&&schema.includes(migration57.trim())&&schema.includes(migration58.trim())&&schema.includes(migration59.trim())&&schema.includes(migration60.trim())&&schema.includes(migration61.trim())&&schema.includes(migration62.trim())&&schema.includes(migration63.trim())&&schema.includes(migration64.trim())&&schema.includes(migration65.trim())&&schema.includes(migration66.trim())&&schema.includes(migration67.trim())&&schema.includes(migration68.trim())&&schema.includes(migration69.trim())&&schema.includes(migration70.trim())&&schema.includes(migration71.trim())&&schema.includes(migration72.trim())&&schema.includes(migration73.trim())&&schema.includes(migration74.trim())&&schema.includes('SOURCE: 075_deep_qa_autoheal_v4567.sql'),'Consolidated production schema must preserve migrations 037-073 and include migration 074 before current migration 075');
assert.ok(migration44.includes("active_release_version='4.5.14'")&&migration44.includes("('4.5.14','Final release candidate"),'Migration 044 must set the v4.5.14 release marker');
assert.ok(migration45.includes("active_release_version='4.5.15'")&&migration45.includes("('4.5.15','Account protection and MFA runtime fix"),'Migration 045 must set the v4.5.15 release marker');
assert.ok(migration46.includes("active_release_version='4.5.16'")&&migration46.includes("('4.5.16','Release-evidence correction"),'Migration 046 must set the v4.5.16 release marker');
assert.ok(migration47.includes("active_release_version='4.5.17'")&&migration47.includes("('4.5.17','Accounting management-result"),'Migration 047 must set the v4.5.17 release marker');
assert.ok(migration48.includes("active_release_version='4.5.18'")&&migration48.includes("('4.5.18','Accounting Tax runtime restoration"),'Migration 048 must set the v4.5.18 release marker');
assert.ok(migration49.includes("active_release_version='4.5.19'")&&migration49.includes("('4.5.19','Accessibility labels"),'Migration 049 must set the v4.5.19 release marker');
assert.ok(migration50.includes("active_release_version='4.5.20'")&&migration50.includes("('4.5.20','Semantic full-width desktop table columns"),'Migration 050 must set the v4.5.20 release marker');
assert.ok(migration51.includes("active_release_version='4.5.21'")&&migration51.includes("('4.5.21','Deep audit closure"),'Migration 051 must set the v4.5.21 release marker');
for(const marker of ['POSTED_JOURNAL_IMMUTABLE','ACCOUNTING_POST_PERMISSION_REQUIRED','ACCOUNTING_PERIOD_UNLOCK_REASON_REQUIRED','TIMESHEET_APPROVE_PERMISSION_REQUIRED','PROCUREMENT_APPROVE_PERMISSION_REQUIRED'])assert.ok(migration51.includes(marker),`Migration 051 missing ${marker}`);
assert.ok(migration52.includes("active_release_version='4.5.25'")&&migration52.includes("('4.5.25','QA closure release"),'Migration 052 must set the v4.5.25 release marker');
assert.ok(migration53.includes("active_release_version='4.5.26'")&&migration53.includes("('4.5.26','Engineering QA release"),'Migration 053 must retain the v4.5.26 release marker');
assert.ok(migration54.includes("active_release_version='4.5.27'")&&migration54.includes("('4.5.27','Production invariant hardening"),'Migration 054 must set the v4.5.27 release marker');
console.log(`PASS v4.5.27 server validation covers ${expectedCollections.length} namespaces plus transition-specific authorization and entity integrity`);
