import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const sql=fs.readFileSync(path.join(root,'supabase/migrations/055_financial_reporting_integrity_v4536.sql'),'utf8');
assert.match(sql,/balance_sheet_class/);
assert.match(sql,/s:=fy-1/);
assert.doesNotMatch(sql,/s\s+date\s*:=\s*p_from-1/i);
assert.match(sql,/account_balance_at_excluding\(cid,'214','2147'/);
assert.match(sql,/\('230','Bất động sản đầu tư'/);
assert.match(sql,/o_long_inv:=app\.account_balance_at\(cid,'228'/);
assert.doesNotMatch(sql,/o_long_inv[^;]*'217'/);
assert.match(sql,/expected='inflow' and cash_net<=0/);
assert.match(sql,/expected='outflow' and cash_net>=0/);
assert.match(sql,/where status='approved'/);
assert.match(sql,/B03_DIRECTION/);
assert.match(sql,/B01_CLASSIFICATION/);
console.log('PASS v4.5.36 SQL financial reporting integrity guards');
