import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const sql=fs.readFileSync(path.join(root,'supabase/migrations/058_statutory_template_manager_filter_chart_tax_v4540.sql'),'utf8');
for(const required of ["('4.5.40'",'create table if not exists public.statutory_report_templates','package_sha256 text not null','enable row level security',"app.has_permission('reports.import'", "app.current_aal()<>'aal2'", "p_release_version<>'4.5.40'",'p_migration_version<>58'])assert.ok(sql.includes(required),`Missing SQL control: ${required}`);
assert.ok(/revoke all on public\.statutory_report_templates from public,anon/i.test(sql));
assert.ok(/grant select,insert,update on public\.statutory_report_templates to authenticated/i.test(sql));
console.log('PASS migration 058 statutory template storage, RLS, MFA activation and release binding');
