import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {webcrypto} from 'node:crypto';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const app=fs.readFileSync(path.join(root,'app.js'),'utf8');
const css=fs.readFileSync(path.join(root,'alpha-design-system.css'),'utf8');
const code=fs.readFileSync(path.join(root,'statutory-template-manager.js'),'utf8');
const pkg=JSON.parse(fs.readFileSync(path.join(root,'templates/statutory/TT133_2026_BASELINE_TEMPLATE.json'),'utf8'));
const ctx={window:{},crypto:webcrypto,TextEncoder,TextDecoder,Blob,DecompressionStream,console};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(code,ctx);
const M=ctx.AlphaStatutoryTemplateManager;
assert.ok(M,'Template manager not exported');
const valid=await M.validatePackage(pkg);assert.equal(valid.valid,true,valid.errors?.join('\n'));
const db={settings:{accountingRegime:'TT133'},statutoryReportTemplates:[]};
const rec=M.install(db,valid,'QA');assert.equal(rec.status,'candidate');M.activate(db,rec.id,'QA');assert.equal(rec.status,'active');assert.equal(db.settings.activeStatutoryTemplateId,rec.id);
const source={form:'B01a-DNN',rows:[{code:'100',label:'OLD',value:1},{code:'110',label:'OLD2',value:2}]};
const mapped=M.applyReport(source,rec,'B01a-DNN');assert.notEqual(mapped.rows[0].label,'OLD');assert.deepEqual(mapped.rows.map(x=>x.value),[1,2],'Template must not alter calculation values');
const hostile=structuredClone(pkg);hostile.reports['B01a-DNN'].rows[0].formula='javascript:alert(1)';const rejected=await M.validatePackage(hostile);assert.equal(rejected.valid,false,'Executable formula must be rejected');
assert.ok(!app.includes("field('citRateMode'"),'Obsolete automatic/manual CIT selector must be removed');
assert.ok(!app.includes('Điều kiện áp dụng mức 15% / 17%'),'Obsolete reduced-rate eligibility selector must be removed');
assert.ok(app.includes('corporateTaxRateEffectiveDate')&&app.includes('citManualRateHistory'),'Effective-dated manual CIT controls are missing');
assert.ok(app.includes('writeTableFilterState(stateKey'),'Filter state persistence missing');
assert.ok(!app.includes('host.innerHTML=tableFn(rows);bindViewEvents()'),'Filtered table rerender recursively resets all filters');
assert.ok(!app.includes('<h2>Số nhân sự theo bộ môn</h2>'),'Duplicate headcount chart should be removed in VERSION FINAL');
assert.ok(app.includes('Cơ cấu phòng ban')&&app.includes('departmentStructure(active)'),'Detailed department structure is missing');
console.log('PASS inherited statutory template safety, manual effective-dated CIT, persistent filters and consolidated department structure');
